version: '3.7'
services:
    app:
      restart: always
      build:
        context:  ./app
        dockerfile: Dockerfile
      volumes:
        - /usr/src/app            
      networks:
        - dbnet        
      depends_on:
        - db_bot

    db_bot:
        image: postgres:12
        restart: always
        env_file:
          - app/.env
        networks:
          - dbnet
        ports:
          - "55432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data/

    proxy:
      restart: always
      build:
        context:  ./nginx
        dockerfile: Dockerfile
      ports:
        - "8180:80"
      links:
        - app
      depends_on:
        - app
        - db_bot
      networks:
        - dbnet        

volumes:
  postgres_data:

networks:
  dbnet: